apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "1000m"
    requests.memory: 1Gi
    limits.cpu: "1500m"
    limits.memory: 1500Mi
    pods: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limits
  namespace: dev
spec:
  limits:
    - default:
        cpu: "300m"
        memory: 256Mi
      defaultRequest:
        cpu: "100m"
        memory: 128Mi
      type: Container
